### ISSUE TITLE
Update for more recent version of shadow-client?

### ISSUE THREAD

**Issue by sogaiu** [thheller/reagent-test#1]
I see shadow-client 1.3.2 on clojars, but this example appears to be using 1.0.180.  I tried updating project.clj, but didn't succeed in sorting out all of what needed to be changed.

Please update reagent-test so it works with shadow-client 1.3.2 or something close to it.

Thanks for your consideration.

**Comment by thheller** [comment]
This is a really old test repo. How did you even find it?

And what in particular were you looking for? The `shadow.markup` example? Nothing there has changed and I suspect the breakage is coming from somewhere else. I'd recommend starting with https://github.com/shadow-cljs/quickstart-browser and just adding a newer reagent version. That should be enough.

**Comment by sogaiu** [comment]
I found the repos via the following:

https://groups.google.com/forum/#!topic/clojurescript/sc-0hukwfpw

I was interested in using shadow.markup as you suggested - the repos works as-is, but I wanted to work with a more recent version of shadow-client.

I'll take a look at your recommendation.

Thanks!

**Comment by thheller** [comment]
I updated the example to use `shadow-cljs` instead which eliminated a whole bunch of complicated config.

`shadow-cljs` itself depends on the most recent version of `shadow-client` that is why it is not included in the `:dependencies` manually but that would be fine too.

I also changed the media query setup to how I use it in my projects nowadays.
